import = [
  # "~/.config/alacritty/themes/hyper.toml",
  # "~/.config/alacritty/themes/one_john.toml",
  "~/.config/alacritty/themes/horizon_dark.toml",
  # "~/.config/alacritty/themes/one_dark.toml",
]

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/local/bin/fish"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
title = "Haxor"
decorations = "None"
padding = { x = 5, y = 5 }

[font]
normal = { "family" = "Mononoki Nerd Font", "style" = "Regular" }
italic = { "family" = "Mononoki Nerd Font", "style" = "Italic" }
size = 18.0
